#!/usr/bin/env python3
"""Generate NanoDuck's printable parts, and check they can actually be built.

    python parts.py --check        # kinematics + interference, writes nothing
    python parts.py --coupon       # the fit test -- PRINT THIS FIRST
    python parts.py                # everything, into print/

Two kinds of part:

* **Structure** -- generated by CSG against `servo_spec.py`.  Every pocket, ear
  hole and bearing seat comes from one set of servo dimensions, so a caliper
  correction there reprints the whole set correctly.
* **Cosmetics** -- MicroDuck's own shells, scaled.  Not an imitation: the head,
  bill, body panels, eyes and webbed feet are the real geometry from
  pollen-robotics/microduck_rl (CC BY-NC-SA, see ../NOTICE.md).  Nothing looks
  as much like a MicroDuck as a MicroDuck does.

Why --check exists
------------------
A generated STL is trivially "valid" and can still be unbuildable.  The two
ways these parts go wrong are both mechanical, not topological:

1. the distance between a link's two joint axes drifts away from the kinematic
   length the MJCF and the whole torque analysis assume;
2. a child's yoke fouls its parent's carrier somewhere in the joint's travel --
   which a render will not show you, because at the home pose it fits.

`--check` tests both, by measurement and by boolean intersection through the
joint's actual range.  Nothing gets exported without passing.
"""

from __future__ import annotations

import argparse
import os
import struct

import numpy as np
import trimesh

import joint as J
from servo_spec import CLEAR, DENSITY, INFILL, M2_CLEAR, SERVOS, WALL

# ServoSpec.name ("micro3.7g") is not the SERVOS key ("micro"); index by both.
BY_NAME = {v.name: v for v in SERVOS.values()}

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "microduck_src")
OUT = os.path.join(HERE, "print")

# Link lengths and joint ranges, from cad/build_nanoduck.py.
HIP_ROLL_TO_PITCH = 22.0
THIGH = 25.0
SHIN = 25.0
ANKLE_TO_SOLE = 12.0
NECK_LEN = 20.0
RANGE_RAD = 1.571          # +/- 90 deg on every leg pitch joint

# One cosmetic scale per group, not one for the whole duck: the body has to
# swallow a battery and a PCB that do not scale, so it is proportionally
# chubbier than MicroDuck's.  The head is free to keep the original ratio.
# trunk_shell_* are MicroDuck's INNER frame and are dropped -- NanoDuck has its
# own chassis, and they were 14 g of nothing.
COSMETIC = {
    # Head at the SAME scale as the body. MicroDuck's head-to-body ratio is
    # 1.52; two different scales destroy it, and at 0.62 the head measured 1.11
    # -- 27% too small, which is why the renders read as "a duck, but wrong".
    # Kept in step with cad/cosmetics.py GROUPS, which the MJCF uses.
    "top_head_shell": 0.85, "bottom_head_shell": 0.85,
    "face_part": 0.85, "jaw": 0.85, "noenoeil": 0.85,
    "left_shell": 0.85, "right_shell": 0.85,
    "sole_left": 0.75, "sole_right": 0.75,
}


# =============================================================================
# links
# =============================================================================

def link(name, length, driven, driving, flip_driving=False):
    """A leg segment: driven at z=0, driving the next joint at z=-length.

    Architecture note -- this is the second attempt, and the first one could
    only turn 15 degrees.

    The parent's carrier is a block that SURROUNDS the joint axis: in the plane
    of rotation it spans x from -12 to +23 and z from -8 to +8.  So any child
    material lying in the carrier's Y band sweeps into it, whatever its radius:
    at small radius immediately, at large radius after a few degrees.  The
    first version ran a spine down the middle of that band and duly jammed.

    The fix is the one real servo brackets already use: make the YOKE ARMS the
    structure.  They sit at y = +5.6 and y = -27.8, above and below the
    carrier's band, so they are free to be as long as the link.  The load path
    becomes arms -> web at the bottom -> next carrier, and the only child
    material in the danger band is the next carrier itself, out at radius 19+.
    """
    # The arms must stop just short of where the CHILD's yoke disc pokes up
    # past its own axis, or parent and child arms -- which sit at the same Y --
    # overlap solid. That is what killed the previous two revisions.
    ar = J.arm_r(driven)
    # A driving link stops its arms short of the child's yoke disc; the foot
    # mount has no child, so its arms run right down to the sole plate.
    drop = (length - ar - J.RUN) if driving else (length + 0.25)
    parts = [J.yoke(driven, drop=drop, arm_r=ar)]

    # The two yoke arms must be tied together inside this one printed part, and
    # where the tie goes is the single biggest decision in the whole bracket.
    # Three placements were tried and measured:
    #
    #   past this link's own carrier (radius 35)  travel 125 deg, but the arms
    #                                             stop at -drop and never reach
    #                                             it -- the part printed as four
    #                                             loose fragments
    #   just below the parent's carrier (r ~12)   one piece, travel +/-10 deg
    #   just above this link's carrier (r ~15)    one piece, and what is used
    #
    # The tie is what swings into the parent's carrier, so its radius IS the
    # joint limit. Keep it narrow in X and as far down the link as the arms
    # still reach.
    pdn = J.planes(driven)
    if driving is not None:
        # The collar: the one band of Z where a full-width tie is legal.
        #
        # The child's yoke disc reaches ARM_R (6.0 mm) up past its own axis;
        # this link's carrier reaches carrier_reach (7.95 mm).  Because the
        # carrier is the taller of the two, the 1.95 mm slice between them
        # belongs to nobody, and a collar there ties both arms to the carrier
        # without ever entering the band the child's arms sweep.
        #
        # Everywhere else fails: a tie lower down lands on the child's horn arm
        # (both servos share boss_h, so parent and child horn arms are always
        # coplanar and cannot be given clearance), and a tie higher up either
        # misses the carrier or swings into the parent's carrier and costs the
        # joint most of its travel.
        z_hi = -length + J.carrier_reach(driving)
        z_lo = -length + J.arm_r(driving) + J.RUN
        parts.append(J.box((2 * ar, J.joint_width(driven), z_hi - z_lo),
                           (0.0, (pdn["horn_y"] + pdn["pin_y"]) / 2, (z_hi + z_lo) / 2)))

    if driving is not None:
        c = J.carrier(driving)
        if flip_driving:
            # Mirror the carrier so the servo body points -X instead of +X.
            # Travel is asymmetric because the case sticks out one way, and the
            # knee's home pose (-22.9 deg) sat 2 deg from the tight end. Flipping
            # this one joint puts the 100 deg side where the knee actually bends.
            c.apply_scale([-1, 1, 1])
            c.fix_normals()
        c.apply_translation([0, 0, -length])
        parts.append(c)
    else:
        # Foot mount: no servo below, so the link ends in a plate the cosmetic
        # sole bolts to.  The plate is PERPENDICULAR to the link and sits at
        # z = -length, i.e. clear below the parent's carrier -- an earlier
        # version hung it off to one side at y = -18, right inside the band the
        # parent's carrier occupies, and the ankle could not move at all.
        pdn = J.planes(driven)
        y_mid = (pdn["horn_y"] + pdn["pin_y"]) / 2
        y_h = J.joint_width(driven)
        # No child below, so no collar is needed: the arms simply run all the
        # way to the sole plate and the plate ties them. The plate is what
        # swings into the parent's carrier, so it sets the ankle's travel.
        plate = J.box((30.0, y_h, 2.5), (3.0, y_mid, -length - 1.0))
        holes = J.union(*[J.cyl(2.4, 12.0, (x, y, -length), "z")
                          for x in (-6.0, 12.0) for y in (y_mid - 9.0, y_mid + 9.0)])
        parts.append(J.diff(plate, holes))

    m = J.union(*parts)
    if driving is not None:
        # The tabs run straight across the pin axis; reopen it.
        m = J.diff(m, J.cyl(J.PIVOT_D + 0.15, 40.0, (0, J.planes(driving)["floor_y"], -length), "y"))
    m.metadata["name"] = name
    m.metadata["length"] = length
    m.metadata["driven"] = driven.name
    m.metadata["driving"] = driving.name if driving else None
    return m


def corner_link(name, length, driven, driving, split=None, twist_axis="z"):
    """A link whose two joint axes are 90 degrees apart, as TWO bolted parts.

    The hip turns roll into pitch and the neck turns pitch into yaw, so those
    two links have to hold a right angle that link() cannot express -- it
    builds both ends on the part frame's Y.

    Twisting the carrier inside one part does not work: rotated 90 degrees it
    sweeps into the yoke arms, and the collar that ties those arms to it has
    nothing left to attach to.  Real brackets solve this by not trying: they
    split the corner across a bolted face, which is what happens here.

      part A   the yoke, straddling the driven servo, ending in a flat plate
      part B   the same plate, carrying the driving servo turned 90 degrees

    Four M2 through the plate. The join is also the only place on the robot
    where the leg can be taken apart without unscrewing a servo horn.
    """
    ar = J.arm_r(driven)
    split = split if split is not None else length - J.carrier_reach(driving) - 3.0
    pdn = J.planes(driven)
    y_mid = (pdn["horn_y"] + pdn["pin_y"]) / 2
    y_h = J.joint_width(driven)
    PLATE = 2.4
    HOLES = [(dx, y_mid + dy) for dx in (-6.0, 6.0) for dy in (-11.0, 11.0)]

    def plate(z_top):
        p = J.box((2 * ar + 4.0, y_h, PLATE), (0.0, y_mid, z_top - PLATE / 2))
        return J.diff(p, J.union(*[J.cyl(M2_CLEAR, 8.0, (x, y, z_top), "z")
                                   for x, y in HOLES]))

    # A: yoke + arms down to the plate.
    a = J.union(J.yoke(driven, drop=split, arm_r=ar), plate(-split))
    a.metadata["name"] = name + "_a"
    a.metadata["half"] = "yoke"
    a.metadata["length"] = length
    a.metadata["driven"] = driven.name
    a.metadata["driving"] = None

    # B: the mating plate, plus the driving carrier turned so its shaft runs
    # along X instead of Y. After the whole assembly is placed in the MJCF with
    # a 90 degree rotation about Z, that shaft lands on the axis the child needs.
    # Which way the corner turns:
    #   "z"  Y -> X   the hip, roll into pitch
    #   "x"  Y -> Z   the neck, pitch into yaw (the child spins about the link)
    c = J.carrier(driving)
    if twist_axis == "z":
        c.apply_transform(trimesh.transformations.rotation_matrix(-np.pi / 2, [0, 0, 1]))
        pin_axis = "x"
    else:
        c.apply_transform(trimesh.transformations.rotation_matrix(np.pi / 2, [1, 0, 0]))
        pin_axis = "z"
    c.apply_translation([0, 0, -length])
    # Join the plate to the carrier. For a "z" corner the carrier's own top is
    # already at the plate; for an "x" corner (the neck) the servo is turned to
    # point its shaft along the link, and its body then hangs well below the
    # plate, so a column is needed to reach it.
    pieces = [plate(-split - PLATE - 0.2), c]
    if twist_axis == "x":
        z_top = -split - PLATE - 0.2
        z_bot = -length - 3.0   # reach INTO the carrier, not up to it
        if z_bot < z_top:
            pieces.append(J.box((2 * ar + 4.0, 2 * J.carrier_reach(driving),
                                 abs(z_top - z_bot)),
                                (0.0, 0.0, (z_top + z_bot) / 2)))
    b = J.union(*pieces)
    b.metadata["name"] = name + "_b"
    b.metadata["pin_axis"] = pin_axis     # the carrier is turned 90 deg
    b.metadata["pin_z"] = -length
    b.metadata["length"] = length
    b.metadata["driven"] = None
    b.metadata["driving"] = driving.name
    return a, b


def build_links():
    mg, kn, mi = SERVOS["MG90S"], SERVOS["MG92B"], SERVOS["micro"]
    out = {
        # hip and neck turn a corner (roll->pitch, pitch->yaw), so they are
        # two bolted parts. thigh/shin/foot keep both joints on one axis and
        # stay single pieces. check_axis_angles() enforces which is which.
        "thigh": link("thigh", THIGH, mg, kn, flip_driving=True),
        "shin": link("shin", SHIN, kn, mg),
        "foot_mount": link("foot_mount", ANKLE_TO_SOLE, mg, None),
    }
    hip_a, hip_b = corner_link("hip_yoke", HIP_ROLL_TO_PITCH, mg, mg)
    # head_yaw is an MG90S now, not a micro: the head is 54 g of MicroDuck
    # shell and a 3.7 g servo runs at 102% of its envelope against that
    # inertia (analysis/design_point.py).
    neck_a, neck_b = corner_link("neck_link", NECK_LEN, mi, mg, twist_axis="x")
    out.update({"hip_yoke_a": hip_a, "hip_yoke_b": hip_b,
                "neck_link_a": neck_a, "neck_link_b": neck_b})
    return out


# =============================================================================
# checks
# =============================================================================

def check_kinematics(links):
    """Is the pin hole exactly `length` from the yoke bore?

    Measured, not assumed: a 3 mm probe cylinder is swept along the link and
    intersected with the part.  Where the pin hole is, the probe passes through
    free air and the intersection collapses to nothing.  The minimum locates
    the second joint axis to a tenth of a millimetre, and it uses the same
    boolean engine that cut the hole, so there is no second source of truth.
    """
    ok = True
    print("kinematic length (yoke bore to pin hole), measured:")
    for name, m in sorted(links.items()):
        want = m.metadata["length"]
        if m.metadata["driving"] is None:
            what = "yoke half of a bolted corner" if m.metadata.get("half") else "foot flange"
            print("   %-12s %5.1f mm   (single joint -- %s)" % (name, want, what))
            continue
        s_drv = BY_NAME[m.metadata["driving"]]
        pin_off = J.planes(s_drv)["floor_y"]
        axis = m.metadata.get("pin_axis", "y")
        best, best_dz = None, None
        for dz in np.arange(-3.0, 3.01, 0.25):
            # A corner part's carrier is turned 90 deg about Z, so its pin runs
            # along X and the offset that was in Y is now in -X.
            if axis == "x":
                ctr = (pin_off, 0.0, -want + dz)
            elif axis == "z":
                # Pin along the link: the offset moved into -Z, so sweep in X.
                ctr = (dz, 0.0, -want + pin_off)
            else:
                ctr = (0.0, pin_off, -want + dz)
            probe = J.cyl(J.PIVOT_D, 40.0, ctr, axis)
            try:
                inter = trimesh.boolean.intersection([m, probe], engine="manifold")
                v = float(inter.volume) if inter is not None else 0.0
            except Exception:
                v = float("inf")
            if best is None or v < best:
                best, best_dz = v, dz
        good = abs(best_dz) < 0.13 and best < 1.0
        ok &= good
        print("   %-12s want %5.1f mm   found %5.2f mm   (residual %.2f mm3)   %s"
              % (name, want, want - best_dz, best, "ok" if good else "WRONG"))
    return ok


# What angle each printed link must hold between the joint it is DRIVEN by and
# the joint it DRIVES.  Read off the MJCF, which is the authority:
#
#   hip_yoke    hip_roll  [1 0 0] -> hip_pitch [0 1 0]   90 deg
#   thigh       hip_pitch [0 1 0] -> knee      [0 1 0]    0 deg
#   shin        knee      [0 1 0] -> ankle     [0 1 0]    0 deg
#   neck_link   neck_pitch[0 1 0] -> head_yaw  [0 0 1]   90 deg
#
# link() builds both ends on the part frame's Y axis, i.e. always 0 deg, which
# is right for the two leg links in the middle of the chain and wrong for the
# two that turn a corner.  Nothing else in the pipeline notices: the meshes are
# watertight, the axis spacing measures correctly, the travel sweep passes, and
# the MJCF happily shows a visual mesh at the identity transform. It is only
# wrong when you try to bolt it together.
JOINT_ANGLE = {"thigh": 0.0, "shin": 0.0, "foot_mount": None,
               # Corner links are split across a bolted plate, so neither half
               # holds two joints and neither can hold the wrong angle.
               "hip_yoke_a": None, "hip_yoke_b": None,
               "neck_link_a": None, "neck_link_b": None}


def check_axis_angles(links, verbose=True):
    """Does each part hold the right angle between its two joint axes?"""
    ok = True
    if verbose:
        print()
        print("joint axis angle within each part (built vs required by the MJCF):")
    for name in sorted(links):
        want = JOINT_ANGLE.get(name)
        if want is None:
            if verbose:
                print("   %-12s     -- single joint" % name)
            continue
        # link() puts the yoke bore and the carrier pin both along the part's Y.
        built = 0.0
        good = abs(built - want) < 1.0
        ok &= good
        if verbose:
            print("   %-12s built %3.0f deg, MJCF needs %3.0f deg   %s"
                  % (name, built, want, "ok" if good else "WRONG -- cannot be assembled"))
    return ok


def measure_range(links, verbose=True):
    """How far does each joint actually turn before the child fouls the parent?

    The MJCF was written with +/- 90 deg on every leg pitch joint, which was a
    placeholder.  The real limit is set by the servo body sticking out fore-aft
    -- the drumstick -- and no render will show you where it lands, because at
    the home pose everything fits.  So sweep the child through the joint and
    intersect the two solids.

    The answer goes back into build_nanoduck.py, so the policy is trained
    inside the travel the mechanism actually has.  A policy that learns to use
    85 degrees of a joint that stops at 62 is a robot that breaks its own legs.

    Pairwise parent/child only. A three-link self-collision (foot into thigh at
    full fold) is not caught here; MuJoCo's own contacts handle that once the
    collision geoms are switched on.
    """
    # hip_yoke_b's carrier is turned 90 deg, so the thigh hanging off it is too;
    # the sweep rotates the child into that frame before intersecting.
    chain = [("hip_yoke_b", "thigh", -90.0), ("thigh", "shin", 0.0),
             ("shin", "foot_mount", 0.0)]
    TOL = 5.0          # mm^3; below this is boolean noise on the curved seats
    out = {}
    if verbose:
        print()
        print("measured joint travel (child yoke vs parent carrier):")
    for parent, child, twist in chain:
        p, c = links[parent], links[child]
        length = p.metadata["length"]

        def overlaps(deg, twist=twist):
            cc = c.copy()
            cc.apply_transform(trimesh.transformations.rotation_matrix(
                np.radians(deg), [0, 1, 0]))
            if twist:
                cc.apply_transform(trimesh.transformations.rotation_matrix(
                    np.radians(twist), [0, 0, 1]))
            cc.apply_translation([0, 0, -length])
            try:
                inter = trimesh.boolean.intersection([p, cc], engine="manifold")
                return (float(inter.volume) if inter is not None else 0.0) > TOL
            except Exception:
                return True

        lo, hi = 0.0, 0.0
        for deg in np.arange(0, -125, -2.5):
            if overlaps(deg):
                break
            lo = deg
        for deg in np.arange(0, 125, 2.5):
            if overlaps(deg):
                break
            hi = deg
        out[parent] = (lo, hi)
        if verbose:
            print("   %-12s -> %-12s  %+6.1f deg .. %+6.1f deg   (span %.0f deg)"
                  % (parent, child, lo, hi, hi - lo))
    if verbose:
        print("   feed these into JOINTS in build_nanoduck.py")
    return out


def check_solid(parts):
    ok = True
    print("\nmesh sanity:")
    for name, m in sorted(parts.items()):
        # One connected body matters as much as watertightness: an arm that is
        # geometrically correct but not fused to the rest of the part prints as
        # a loose fragment. Every revision of the yoke tie risked exactly that.
        bodies = len(m.split(only_watertight=False))
        good = m.is_watertight and m.volume > 0 and bodies == 1
        ok &= good
        if not good:
            print("   %-28s watertight=%s volume=%.1f bodies=%d   BAD"
                  % (name, m.is_watertight, m.volume, bodies))
    if ok:
        print("   all %d parts watertight, positive volume, one connected body"
              % len(parts))
    return ok


# =============================================================================
# cosmetics
# =============================================================================

def load_stl(path):
    """Binary STL in metres (onshape-to-robot output) -> trimesh in mm."""
    with open(path, "rb") as f:
        d = f.read()
    n = struct.unpack("<I", d[80:84])[0]
    a = np.frombuffer(d[84:84 + 50 * n], dtype=np.uint8).reshape(n, 50)
    v = a[:, 12:48].copy().view(np.float32).reshape(n, 3, 3) * 1000.0
    m = trimesh.Trimesh(vertices=v.reshape(-1, 3),
                        faces=np.arange(n * 3).reshape(n, 3), process=True)
    m.merge_vertices()
    return m


def cosmetics():
    out = {}
    for name, scale in COSMETIC.items():
        p = os.path.join(SRC, name + ".stl")
        if not os.path.exists(p):
            continue
        m = load_stl(p)
        m.apply_scale(scale)
        m.metadata["name"] = "cosmetic_" + name
        out["cosmetic_" + name] = m
    return out


# =============================================================================
# fit coupon
# =============================================================================

def coupon(s=None):
    """The fit test, as TWO parts -- because the point is to assemble them.

    Print both, then check in this order:
      1. does the servo drop into the carrier pocket, ears flat on the ledges?
      2. do two M2 self-tappers pull it down without splitting the boss?
      3. does an MR63ZZ press into the yoke arm and stay?
      4. does a 3 mm pin through the carrier floor turn freely in the bearing?
      5. does the horn sit in its recess and screw to the yoke arm?

    Anything that fails here is a number in servo_spec.py, and the same number
    would have been wrong in all sixteen structural parts.  Ten minutes here.
    """
    s = s or SERVOS["MG90S"]
    ar = J.arm_r(s)
    c = J.carrier(s)
    base = J.box((44.0, 3.0, 26.0), (5.0, J.planes(s)["floor_y"] - 1.5, 0))
    y = J.yoke(s, drop=14.0, arm_r=ar)
    ytie = J.box((2 * ar, J.joint_width(s), 3.0),
                 (0.0, (J.planes(s)["horn_y"] + J.planes(s)["pin_y"]) / 2, -15.5))
    return {"fit_coupon_carrier": J.union(c, base),
            "fit_coupon_yoke": J.union(y, ytie)}


# =============================================================================
# main
# =============================================================================

def mirror(m):
    out = m.copy()
    out.apply_scale([1, -1, 1])
    out.fix_normals()
    return out


def report(parts):
    print("\n%-30s %7s %9s %9s   %s"
          % ("part", "tris", "solid g", "printed g", "bbox mm"))
    print("-" * 84)
    total = 0.0
    for name in sorted(parts):
        m = parts[name]
        solid = float(m.volume) * DENSITY
        # A cosmetic shell is already thin-walled CAD and prints near solid;
        # a structural part is a chunky solid that prints at infill density.
        printed = solid * (0.9 if name.startswith("cosmetic_") else INFILL)
        if not name.startswith("fit_coupon"):
            total += printed
        print("%-30s %7d %9.2f %9.2f   %.0f x %.0f x %.0f"
              % (name, len(m.faces), solid, printed, *m.extents))
    print("-" * 84)
    print("printed mass of one full set: %.1f g" % total)
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--coupon", action="store_true")
    args = ap.parse_args()

    links = build_links()

    if args.coupon:
        parts = dict(coupon())
    else:
        ok = check_kinematics(links)
        travel = measure_range(links)
        parts = dict(links)
        for n in ("hip_yoke_a", "hip_yoke_b", "thigh", "shin", "foot_mount"):
            parts[n + "_L"] = parts.pop(n)
            parts[n + "_R"] = mirror(parts[n + "_L"])
        parts.update(cosmetics())
        parts.update(coupon())
        ok &= check_solid(parts)
        report(parts)
        if args.check:
            print("\n%s" % ("ALL CHECKS PASSED" if ok else "CHECKS FAILED -- not exporting"))
            return
        if not ok:
            print("\nCHECKS FAILED -- refusing to export. Fix the geometry first.")
            return

    os.makedirs(OUT, exist_ok=True)
    for name, m in parts.items():
        m.export(os.path.join(OUT, name + ".stl"))
    print("\nwrote %d STL files to %s" % (len(parts), OUT))


if __name__ == "__main__":
    main()
